# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/api" # Location of package manifests
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays
      day: "monday"
    reviewers:
      - "tochiman"
  - package-ecosystem: "npm"
    directory: "/front/brain-quoridor-front"
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays
      day: "monday"
    reviewers:
      - "tochiman"
