services:
  front:
    init: true
    container_name: brain_quoridor_front
    build:
      context: ./front
      dockerfile: Dockerfile
    user: node
    expose:
      - 3000
    volumes:
      - ./front/brain-quoridor-front:/home/node/app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: "yarn dev"
    networks:
      - front

  api:
    container_name: brain_quoridor_api
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 8080
    volumes:
      - ./api/app:/app
    environment:
      - ROOT_PATH=/api
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    networks:
      - api

  nginx:
    container_name: brain_quoridor_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html/
    depends_on:
      - front
      - api
    networks:
      - front
      - api

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.25.0/24
  api:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
